"""add event detail columns to todo

Revision ID: 010c9e942e7e
Revises: f665b0105dcc
Create Date: 2025-06-04 15:31:23.126411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '010c9e942e7e'
down_revision = 'f665b0105dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('todo', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('todo', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('todo', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('todo', sa.Column('reminder', sa.String(length=32), nullable=True))
    op.add_column('todo', sa.Column('repeat', sa.String(length=32), nullable=True))
    op.add_column('todo', sa.Column('tag', sa.String(length=64), nullable=True))
    op.add_column('todo', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('todo', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('todo', 'extra')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('extra', mysql.TEXT(), nullable=True))
    op.drop_column('todo', 'description')
    op.drop_column('todo', 'location')
    op.drop_column('todo', 'tag')
    op.drop_column('todo', 'repeat')
    op.drop_column('todo', 'reminder')
    op.drop_column('todo', 'end_time')
    op.drop_column('todo', 'start_time')
    op.drop_column('todo', 'end_date')
    op.drop_column('todo', 'start_date')
    # ### end Alembic commands ###
