"""add profile fields to user

Revision ID: 82803415e43a
Revises: d907a68ea90c
Create Date: 2025-06-04 14:54:52.946816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82803415e43a'
down_revision = 'd907a68ea90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'address')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'dob')
    # ### end Alembic commands ###
