"""Add pincode to User

Revision ID: d907a68ea90c
Revises: 4ac8585d96cb
Create Date: 2025-06-04 13:53:41.556082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd907a68ea90c'
down_revision = '4ac8585d96cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pincode', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pincode')
    # ### end Alembic commands ###
