"""add extra field to todo

Revision ID: f665b0105dcc
Revises: 82803415e43a
Create Date: 2025-06-04 15:29:59.483895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f665b0105dcc'
down_revision = '82803415e43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('extra', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'extra')
    # ### end Alembic commands ###
